### ISSUE TITLE
Error 1 when installing guide-docs

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/kuebiko#16]
When running `make serve-guide-docs` I get the following error:

```
rm -r docs/guide/pycco || true
rm: docs/guide/pycco: No such file or directory
find kuebiko -name "*.py" | xargs pycco -p -d docs/guide/pycco -s -i
Traceback (most recent call last):
  File "/opt/anaconda3/envs/kuebiko/bin/pycco", line 5, in <module>
    from pycco.main import main
  File "/opt/anaconda3/envs/kuebiko/lib/python3.8/site-packages/pycco/__init__.py", line 1, in <module>
    from .main import *  # noqa
  File "/opt/anaconda3/envs/kuebiko/lib/python3.8/site-packages/pycco/main.py", line 60, in <module>
    from pycco.generate_index import generate_index
  File "/opt/anaconda3/envs/kuebiko/lib/python3.8/site-packages/pycco/generate_index.py", line 9, in <module>
    from pycco_resources import pycco_template
  File "/opt/anaconda3/envs/kuebiko/lib/python3.8/site-packages/pycco_resources/__init__.py", line 1, in <module>
    import pystache
  File "/opt/anaconda3/envs/kuebiko/lib/python3.8/site-packages/pystache/__init__.py", line 2, in <module>
    from init import *
ModuleNotFoundError: No module named 'init'
make: *** [pycco] Error 1
```

Which is odd because there is a `init` module in the installation of `pystache`.

**Comment by bishax** [comment]
Odd indeed.

What's the output of `conda env export`?

**Comment by Juan-Mateos** [comment]
```
name: kuebiko
channels:
  - defaults
dependencies:
  - ca-certificates=2021.9.30=hecd8cb5_1
  - certifi=2021.10.8=py38hecd8cb5_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1l=h9ed2024_0
  - pip=21.2.4=py38hecd8cb5_0
  - python=3.8.12=h88f2d9e_0
  - readline=8.1=h9ed2024_0
  - setuptools=58.0.4=py38hecd8cb5_0
  - sqlite=3.36.0=hce871da_0
  - tk=8.6.11=h7bc2e8c_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - alabaster==0.7.12
    - appnope==0.1.2
    - astroid==2.8.3
    - attrs==21.2.0
    - awscli==1.21.1
    - babel==2.9.1
    - backcall==0.2.0
    - backports-entry-points-selectable==1.1.0
    - bandit==1.7.0
    - black==21.9b0
    - boto3==1.19.1
    - botocore==1.22.1
    - cfgv==3.3.1
    - charset-normalizer==2.0.7
    - click==8.0.3
    - colorama==0.4.3
    - debugpy==1.5.1
    - decorator==5.1.0
    - distlib==0.3.3
    - docutils==0.15.2
    - entrypoints==0.3
    - filelock==3.3.1
    - flake8==4.0.1
    - flake8-bandit==2.1.2
    - flake8-black==0.2.3
    - flake8-bugbear==21.9.2
    - flake8-import-order==0.18.1
    - flake8-polyfill==1.0.2
    - ghp-import==2.0.2
    - gitdb==4.0.7
    - gitpython==3.1.24
    - identify==2.3.0
    - idna==3.3
    - imagesize==1.2.0
    - importlib-metadata==4.8.1
    - iniconfig==1.1.1
    - ipykernel==6.4.2
    - ipython==7.28.0
    - ipython-genutils==0.2.0
    - isort==5.9.3
    - jedi==0.18.0
    - jinja2==3.0.2
    - jmespath==0.10.0
    - jsonschema==4.1.2
    - jupyter-client==7.0.6
    - jupyter-core==4.8.1
    - jupytext==1.13.0
    - lazy-object-proxy==1.6.0
    - markdown==3.3.4
    - markdown-it-py==1.1.0
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mccabe==0.6.1
    - mdit-py-plugins==0.2.8
    - mergedeep==1.3.4
    - metaflow==2.3.6
    - mkdocs==1.2.3
    - mkdocs-material==7.3.4
    - mkdocs-material-extensions==1.0.3
    - mypy-extensions==0.4.3
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - nodeenv==1.6.0
    - numpy==1.21.3
    - packaging==21.0
    - pandas==1.3.3
    - parso==0.8.2
    - pathspec==0.9.0
    - pbr==5.6.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.4.0
    - pluggy==1.0.0
    - pockets==0.9.1
    - pre-commit==2.15.0
    - pre-commit-hooks==4.0.1
    - prompt-toolkit==3.0.21
    - ptyprocess==0.7.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pycco==0.6.0
    - pycodestyle==2.8.0
    - pyflakes==2.4.0
    - pygments==2.10.0
    - pylint==2.11.1
    - pymdown-extensions==9.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - pystache==0.5.0
    - pytest==6.2.5
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==5.4.1
    - pyyaml-env-tag==0.1
    - pyzmq==22.3.0
    - regex==2021.10.21
    - requests==2.26.0
    - rsa==4.7.2
    - ruamel-yaml==0.17.16
    - ruamel-yaml-clib==0.2.6
    - s3transfer==0.5.0
    - six==1.16.0
    - smartypants==2.0.1
    - smmap==4.0.0
    - snowballstemmer==2.1.0
    - sphinx==4.2.0
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-napoleon==0.7
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - stevedore==3.5.0
    - toml==0.10.2
    - tomli==1.2.1
    - toolz==0.11.0
    - tornado==6.1
    - traitlets==5.1.0
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - virtualenv==20.8.1
    - watchdog==2.1.6
    - wcwidth==0.2.5
    - wrapt==1.13.2
    - zipp==3.6.0
```

**Comment by bishax** [comment]
This looks like it's a problem with pycco's version specifications

https://github.com/bishax/pycco/blob/de1a1731758a73a5aa6d09b017392ac35c1bbf3a/setup.py#L22

If you `pip install pystache==0.5.4` does it work? If so, I can sort out the version constraints in my pycco fork

**Comment by Juan-Mateos** [comment]
I get:

```
   ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/envs/kuebiko/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tl/ws9177zn3lj_4kjx60w6mkq80000gn/T/pip-install-wkog8ye3/pystache_d0e2f8408dc3442da766fafd55daf735/setup.py'"'"'; __file__='"'"'/private/var/folders/tl/ws9177zn3lj_4kjx60w6mkq80000gn/T/pip-install-wkog8ye3/pystache_d0e2f8408dc3442da766fafd55daf735/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/tl/ws9177zn3lj_4kjx60w6mkq80000gn/T/pip-pip-egg-info-9s95yy_b
         cwd: /private/var/folders/tl/ws9177zn3lj_4kjx60w6mkq80000gn/T/pip-install-wkog8ye3/pystache_d0e2f8408dc3442da766fafd55daf735/
    Complete output (3 lines):
    pystache: using: version '58.0.4' of <module 'setuptools' from '/opt/anaconda3/envs/kuebiko/lib/python3.8/site-packages/setuptools/__init__.py'>
    Warning: 'classifiers' should be a list, got type 'tuple'
    error in pystache setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d6/fd/eb8c212053addd941cc90baac307c00ac246ac3fce7166b86434c6eae963/pystache-0.5.4.tar.gz#sha256=f7bbc265fb957b4d6c7c042b336563179444ab313fb93a719759111eabd3b85a (from https://pypi.org/simple/pystache/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pystache==0.5.4 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4)
ERROR: No matching distribution found for pystache==0.5.4
```

**Comment by bishax** [comment]
So it looks like `setuptools 58` (released last month) removes `use_2to3` standard library module which is whats happening
(https://github.com/pypa/setuptools/issues/2086).

I wasn't hitting this problem because I had `pystache` in my `pip` cache from before this breaking change.

I can now reproduce your issue with `pip install pystache==0.5.4 --no-cache-dir` 

A temporary fix is to pin `setuptools<58` (e.g. in `requirements_dev.txt`).
A mid-term fix is likely to be to swap the dependency to https://github.com/noahmorrison/chevron (but need to check validity/security of this).
